// cmd/fetch-pricing fetches model pricing from OpenRouter and generates pricing_generated.go.
package main

import (
	"encoding/json"
	"fmt"
	"net/http"
	"os"
	"sort"
	"strconv"
	"strings"
	"time"
)

const (
	apiURL     = "https://openrouter.ai/api/v1/models"
	outputFile = "pricing_generated.go"
)

type openRouterModel struct {
	ID      string `json:"id"`
	Pricing struct {
		Prompt     string `json:"prompt"`
		Completion string `json:"completion"`
	} `json:"pricing"`
}

type openRouterResponse struct {
	Data []openRouterModel `json:"data"`
}

type pricingEntry struct {
	ID         string
	Prompt     float64
	Completion float64
}

func main() {
	entries, err := fetchPricing()
	if err != nil {
		fmt.Fprintf(os.Stderr, "warning: fetch failed: %v\n", err)
		// Check if existing file exists; if so, keep it and exit cleanly.
		if _, statErr := os.Stat(outputFile); statErr == nil {
			fmt.Fprintf(os.Stderr, "keeping existing %s\n", outputFile)
			os.Exit(0)
		}
		fmt.Fprintf(os.Stderr, "no existing %s to fall back to\n", outputFile)
		os.Exit(1)
	}

	if err := generateFile(entries); err != nil {
		fmt.Fprintf(os.Stderr, "error writing %s: %v\n", outputFile, err)
		os.Exit(1)
	}

	fmt.Printf("wrote %s with %d models\n", outputFile, len(entries))
}

func fetchPricing() ([]pricingEntry, error) {
	client := &http.Client{Timeout: 30 * time.Second}
	resp, err := client.Get(apiURL)
	if err != nil {
		return nil, fmt.Errorf("HTTP request failed: %w", err)
	}
	defer resp.Body.Close()

	if resp.StatusCode != 200 {
		return nil, fmt.Errorf("HTTP %d from %s", resp.StatusCode, apiURL)
	}

	var data openRouterResponse
	if err := json.NewDecoder(resp.Body).Decode(&data); err != nil {
		return nil, fmt.Errorf("JSON decode failed: %w", err)
	}

	var entries []pricingEntry
	for _, m := range data.Data {
		prompt, err1 := strconv.ParseFloat(m.Pricing.Prompt, 64)
		completion, err2 := strconv.ParseFloat(m.Pricing.Completion, 64)
		if err1 != nil || err2 != nil {
			continue
		}
		if prompt == 0 && completion == 0 {
			continue
		}
		entries = append(entries, pricingEntry{
			ID:         m.ID,
			Prompt:     prompt,
			Completion: completion,
		})
	}

	sort.Slice(entries, func(i, j int) bool {
		return entries[i].ID < entries[j].ID
	})

	return entries, nil
}

func generateFile(entries []pricingEntry) error {
	var b strings.Builder

	now := time.Now().UTC().Format(time.RFC3339)

	b.WriteString("// Code generated by cmd/fetch-pricing; DO NOT EDIT.\n")
	b.WriteString(fmt.Sprintf("// Source: %s\n", apiURL))
	b.WriteString(fmt.Sprintf("// Generated: %s\n\n", now))
	b.WriteString("package anymodel\n\n")

	b.WriteString(fmt.Sprintf("const pricingAsOf = %q\n\n", now))
	b.WriteString(fmt.Sprintf("const pricingModelCount = %d\n\n", len(entries)))

	b.WriteString("// modelPricing maps model IDs to their per-token pricing (USD).\n")
	b.WriteString("// Prices are per-token, not per-million-tokens.\n")
	b.WriteString("var modelPricing = map[string]PricingEntry{\n")
	for _, e := range entries {
		b.WriteString(fmt.Sprintf("\t%q: {Prompt: %s, Completion: %s},\n",
			e.ID,
			formatFloat(e.Prompt),
			formatFloat(e.Completion),
		))
	}
	b.WriteString("}\n")

	return os.WriteFile(outputFile, []byte(b.String()), 0644)
}

// formatFloat renders a float64 in a clean way for Go source.
func formatFloat(f float64) string {
	if f == 0 {
		return "0"
	}
	s := strconv.FormatFloat(f, 'g', -1, 64)
	// Ensure it looks like a float literal (has a dot or 'e').
	if !strings.Contains(s, ".") && !strings.Contains(s, "e") {
		s += ".0"
	}
	return s
}
